#! /bin/sh

LOG_FILE=/var/log/synoflvconv.log
SYNOFLVCONV=/usr/syno/bin/synoflvconv.orig
REQ_ID=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)

now=$(date +"%Y-%m-%d %H:%M:%S")
echo "[$now] [$$] [${REQ_ID}] Calling $0 $* ..." >> ${LOG_FILE} 2>&1

${SYNOFLVCONV} $*
r=$?
now=$(date +"%Y-%m-%d %H:%M:%S")
echo "[$now] [$$] [${REQ_ID}] Got exit-code $r" >> ${LOG_FILE} 2>&1

exit $r
